---
- name: "Install APT packages"
  ansible.builtin.include_tasks: packages_apt.yml
  tags:
    - apt
    - kali
    - packages

- name: "Install Git packages"
  ansible.builtin.include_tasks: packages_git.yml
  tags:
    - git
    - kali
    - packages

- name: "Install Go packages"
  ansible.builtin.include_tasks: packages_go.yml
  tags:
    - go
    - kali
    - packages

- name: "Install Pipx packages"
  ansible.builtin.include_tasks: packages_pipx.yml
  tags:
    - pipx
    - kali
    - packages
