---
- name: "Install packages"
  ansible.builtin.shell: |
    go install {{ item }}
  environment:
    GOBIN: "/usr/local/bin"
  args:
    creates: "/usr/local/bin/{{ item.split('/')[2].split('@')[0] }}"
  async: 120
  poll: 0
  loop: "{{ packages_go }}"
  loop_control:
    label: "{{ item }}"
  tags:
    - go
    - kali
    - packages
