---
- name: "Install packages"
  ansible.builtin.shell: |
    pipx install --global {{ item }}
  register: packages_pipx_install
  changed_when: "'seems to be installed' not in packages_pipx_install.stdout"
  loop: "{{ packages_pipx }}"
  loop_control:
    label: "{{ item }}"
  tags:
    - pipx
    - kali
    - packages
