---
- name: "Install packages"
  ansible.builtin.shell: |
    set -o pipefail
    pipx install --global {{ item }} | grep -q 'seems to be installed' && exit 1
  register: packages_go_install
  async: 120
  poll: 0
  loop: "{{ packages_pipx }}"
  loop_control:
    label: "{{ item }}"
  tags:
    - pipx
    - kali
    - packages
