---
- name: "Install packages"
  ansible.builtin.command: |
    go install {{ item }}
  environment:
    GOBIN: "/usr/local/bin"
  changed_when: true
  async: 120
  poll: 0
  loop: "{{ packages_go }}"
  loop_control:
    label: "{{ item }}"
  tags:
    - go
    - kali
    - packages
