---
- name: "Update cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - apt
    - packages

- name: "Install dotfiles packages"
  ansible.builtin.apt:
    pkg: "{{ packages_apt.dotfiles }}"
  tags:
    - apt
    - packages
    - dotfiles

- name: "Install Kali packages"
  ansible.builtin.apt:
    pkg: "{{ packages_apt.kali }}"
  tags:
    - apt
    - packages
    - kali

- name: "Clean up"
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
  become: true
