---
- name: "Install packages"
  ansible.builtin.shell: |
    pipx install --global {{ item }}
  async: 120
  poll: 0
  loop: "{{ packages_pipx }}"
  loop_control:
    label: "{{ item }}"
  tags:
    - pipx
    - kali
    - packages
