---
- name: "[chrome] Install"
  ansible.builtin.include_tasks: chrome_install.yml
  tags:
    - chrome
    - kali

- name: "[chrome] Config"
  ansible.builtin.include_tasks: chrome_config.yml
  tags:
    - chrome
    - kali

- name: "[chrome] Extensions"
  ansible.builtin.include_tasks: chrome_extensions.yml
  tags:
    - chrome
    - kali
