---
- name: "Installation"
  ansible.builtin.include_tasks: chrome_install.yml
  tags:
    - chrome

- name: "Configuration"
  ansible.builtin.include_tasks: chrome_config.yml
  tags:
    - chrome

- name: "Extensions"
  ansible.builtin.include_tasks: chrome_extensions.yml
  tags:
    - chrome
