---
- name: "Import APT package list"
  ansible.builtin.include_vars: vars.yml

- name: "Update"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "Install packages"
  ansible.builtin.apt:
    pkg: "{{ install_packages_apt }}"
  become: true
