---
- name: "Import external packages"
  ansible.builtin.copy:
    src: files/external_packages.sh
    dest: /tmp/external_packages.sh
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"
    mode: '755'

- name: "Install external packages"
  ansible.builtin.script: /tmp/external_packages.sh
  args:
    executable: /bin/bash
