---
install_packages_git:
  - kerbrute: "https://github.com/ropnop/kerbrute/releases/latest/download/kerbrute_linux_amd64"
  - nvim: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
  - sliver-server: "https://github.com/BishopFox/sliver/releases/latest/download/sliver-server_linux"
  - sliver-client: "https://github.com/BishopFox/sliver/releases/latest/download/sliver-client_linux"
  - docker-compose: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"

install_packages_apt:
  - bat
  - beep
  - bloodhound-ce-python
  - bloodyad
  - chisel
  - dmenu
  - docker.io
  - donut
  - exa
  - feh
  - flameshot
  - fonts-jetbrains-mono
  - fuse
  - fzf
  - gdb
  - gdb-peda
  - ghidra
  - gobuster
  - golang
  - html2text
  - i3-wm
  - jq
  - keepassxc
  - kitty
  - krb5-config
  - krb5-user
  - lftp
  - libpcap-dev
  - libxml2-dev
  - libxslt-dev
  - ltrace
  - lxappearance
  - mingw-w64
  - mono-complete
  - moreutils
  - nishang
  - npm
  - ntpsec-ntpdate
  - polybar
  - rdate
  - remmina
  - rlwrap
  - rofi
  - seclists
  - sshpass
  - sshuttle
  - stow
  - strace
  - xsel
  - zoxide
